In [20]:
import sys
import os

# Get the absolute path to the project directory
project_dir = os.path.abspath("..")

# Append the project directory to sys.path
if project_dir not in sys.path:
    sys.path.append(project_dir)
    
from src.predictionModule.LoadupSamples import LoadupSamples

import pandas as pd
import numpy as np
import polars as pl
import datetime
import seaborn as sns
import lightgbm as lgb
import random
import matplotlib.pyplot as plt
import logging
import time
import re

In [21]:
params = {
    "daysAfterPrediction": None,
    "idxAfterPrediction": 5,
    'timesteps': 60,
    
    "LoadupSamples_tree_scaling_standard": False,
    "LoadupSamples_time_scaling_stretch": False,
    "LoadupSamples_time_inc_factor": 10,
}

In [48]:
timegroup = "group_regOHLCV_to2014"
treegroup = "group_debug"

eval_date = datetime.date(year=2025, month=11, day=14)
evaldates = [eval_date - datetime.timedelta(days=i) for i in range(0, 6)]
start_train_date = datetime.date(year=2014, month=1, day=1)

ls = LoadupSamples(
    train_start_date=start_train_date,
    test_dates=evaldates,
    treegroup=treegroup,
    timegroup=timegroup,
    params=params,
)
lstree = LoadupSamples(
    train_start_date=start_train_date,
    test_dates=evaldates,
    treegroup=treegroup,
    timegroup=None,
    params=params,
)
lstime = LoadupSamples(
    train_start_date=start_train_date,
    test_dates=evaldates,
    treegroup=None,
    timegroup=timegroup,
    params=params,
)

In [49]:
main_path: str = "../src/featureAlchemy/bin/"
treegroup = "group_debug"
timegroup = "group_regOHLCV_to2014"
label = str(2025)
cat = "Tree"
path_npz = main_path + f"{cat}Features_{label}_{treegroup}.npz"
    
data = np.load(path_npz, allow_pickle=True)
meta_data  = data['meta_feat']
feats_data = data['featuresArr']
names_data = data['featuresNames']

# meta polars
meta_pl_loop: pl.DataFrame = pl.DataFrame({
    "date":     meta_data["date"],
    "ticker":   meta_data["ticker"],
    "Close":    meta_data["Close"],
    "AdjClose": meta_data["AdjClose"],
    "Open":     meta_data["Open"],
    "Low":      meta_data["Low"],
    "High":     meta_data["High"],
    "Volume":   meta_data["Volume"],
})
meta_pl_nvda = meta_pl_loop.filter(pl.col("ticker") == "NVDA")
meta_pl_loop.tail(10)

shape: (10, 8)
┌────────────┬────────┬─────────┬──────────┬─────────┬─────────┬─────────┬──────────────┐
│ date       ┆ ticker ┆ Close   ┆ AdjClose ┆ Open    ┆ Low     ┆ High    ┆ Volume       │
│ ---        ┆ ---    ┆ ---     ┆ ---      ┆ ---     ┆ ---     ┆ ---     ┆ ---          │
│ date       ┆ str    ┆ f64     ┆ f64      ┆ f64     ┆ f64     ┆ f64     ┆ f64          │
╞════════════╪════════╪═════════╪══════════╪═════════╪═════════╪═════════╪══════════════╡
│ 2025-11-14 ┆ MAR    ┆ 285.72  ┆ 285.72   ┆ 285.07  ┆ 281.19  ┆ 288.02  ┆ 1.363255e6   │
│ 2025-11-14 ┆ MDLZ   ┆ 56.86   ┆ 56.86    ┆ 57.24   ┆ 56.5166 ┆ 57.66   ┆ 6.853963e6   │
│ 2025-11-14 ┆ MSFT   ┆ 510.18  ┆ 510.18   ┆ 498.23  ┆ 497.44  ┆ 511.6   ┆ 2.8367897e7  │
│ 2025-11-14 ┆ MU     ┆ 246.83  ┆ 246.83   ┆ 231.45  ┆ 231.23  ┆ 255.17  ┆ 3.6020182e7  │
│ 2025-11-14 ┆ NFLX   ┆ 1112.17 ┆ 1112.17  ┆ 1142.73 ┆ 1107.21 ┆ 1142.73 ┆ 4.721197e6   │
│ 2025-11-14 ┆ NVDA   ┆ 190.17  ┆ 190.17   ┆ 182.86  ┆ 180.58  ┆ 191.01  ┆ 1.85094657e8 │
│ 2025-11-14 ┆ QCOM   ┆ 173.98  ┆ 173.98   ┆ 171.775 ┆ 171.4   ┆ 175.69  ┆ 7.945183e6   │
│ 2025-11-14 ┆ REGN   ┆ 693.5   ┆ 693.5    ┆ 697.19  ┆ 685.95  ┆ 699.27  ┆ 906779.0     │
│ 2025-11-14 ┆ SBUX   ┆ 84.78   ┆ 84.78    ┆ 85.61   ┆ 84.0    ┆ 86.5    ┆ 1.3415724e7  │
│ 2025-11-14 ┆ TXN    ┆ 159.33  ┆ 159.33   ┆ 160.5   ┆ 158.3   ┆ 160.88  ┆ 6.040066e6   │
└────────────┴────────┴─────────┴──────────┴─────────┴─────────┴─────────┴──────────────┘

In [50]:
main_path: str = "../src/featureAlchemy/bin/"
treegroup = "group_debug"
timegroup = "group_regOHLCV_to2014"
label = str(2025)
cat = "Time"
path_npz = main_path + f"{cat}Features_{label}_{timegroup}.npz"
    
data = np.load(path_npz, allow_pickle=True)
meta_data  = data['meta_feat']
feats_data = data['featuresArr']
names_data = data['featuresNames']

# meta polars
meta_pl_loop: pl.DataFrame = pl.DataFrame({
    "date":     meta_data["date"],
    "ticker":   meta_data["ticker"],
    "Close":    meta_data["Close"],
    "AdjClose": meta_data["AdjClose"],
    "Open":     meta_data["Open"],
    "Low":      meta_data["Low"],
    "High":     meta_data["High"],
    "Volume":   meta_data["Volume"],
})
meta_pl_loop.get_column("date").is_sorted()
meta_pl_nvda = meta_pl_loop.filter(pl.col("ticker") == "NVDA")
meta_pl_nvda.tail(100)

shape: (100, 8)
┌────────────┬────────┬────────┬────────────┬─────────┬─────────┬─────────┬──────────────┐
│ date       ┆ ticker ┆ Close  ┆ AdjClose   ┆ Open    ┆ Low     ┆ High    ┆ Volume       │
│ ---        ┆ ---    ┆ ---    ┆ ---        ┆ ---     ┆ ---     ┆ ---     ┆ ---          │
│ date       ┆ str    ┆ f64    ┆ f64        ┆ f64     ┆ f64     ┆ f64     ┆ f64          │
╞════════════╪════════╪════════╪════════════╪═════════╪═════════╪═════════╪══════════════╡
│ 2025-06-26 ┆ NVDA   ┆ 155.02 ┆ 155.011251 ┆ 155.975 ┆ 154.0   ┆ 156.715 ┆ 1.98145746e8 │
│ 2025-06-27 ┆ NVDA   ┆ 157.75 ┆ 157.741097 ┆ 156.04  ┆ 155.255 ┆ 158.71  ┆ 2.63234539e8 │
│ 2025-06-30 ┆ NVDA   ┆ 157.99 ┆ 157.981083 ┆ 158.4   ┆ 155.96  ┆ 158.66  ┆ 1.94580316e8 │
│ 2025-07-01 ┆ NVDA   ┆ 153.3  ┆ 153.291348 ┆ 156.29  ┆ 151.49  ┆ 157.2   ┆ 2.13143621e8 │
│ 2025-07-02 ┆ NVDA   ┆ 157.25 ┆ 157.241125 ┆ 152.98  ┆ 152.97  ┆ 157.6   ┆ 1.71224111e8 │
│ …          ┆ …      ┆ …      ┆ …          ┆ …       ┆ …       ┆ …       ┆ …            │
│ 2025-11-10 ┆ NVDA   ┆ 199.05 ┆ 199.05     ┆ 195.11  ┆ 193.79  ┆ 199.94  ┆ 1.98897134e8 │
│ 2025-11-11 ┆ NVDA   ┆ 193.16 ┆ 193.16     ┆ 195.155 ┆ 191.3   ┆ 195.42  ┆ 1.76483327e8 │
│ 2025-11-12 ┆ NVDA   ┆ 193.8  ┆ 193.8      ┆ 195.72  ┆ 191.13  ┆ 195.89  ┆ 1.54935263e8 │
│ 2025-11-13 ┆ NVDA   ┆ 186.86 ┆ 186.86     ┆ 191.05  ┆ 183.85  ┆ 191.44  ┆ 2.07423074e8 │
│ 2025-11-14 ┆ NVDA   ┆ 190.17 ┆ 190.17     ┆ 182.86  ┆ 180.58  ┆ 191.01  ┆ 1.85094657e8 │
└────────────┴────────┴────────┴────────────┴─────────┴─────────┴─────────┴──────────────┘

In [51]:
ls.load_samples(main_path = "../src/featureAlchemy/bin/")
lstree.load_samples(main_path = "../src/featureAlchemy/bin/")
lstime.load_samples(main_path = "../src/featureAlchemy/bin/")

Test date 2025-11-09 not found in the database. Omitting.
Test date 2025-11-09 not found in the database. Omitting.
Test date 2025-11-09 not found in the database. Omitting.

In [52]:
train_Xtree = ls.train_Xtree
train_ytree = ls.train_ytree
train_Xtime = ls.train_Xtime
train_ytime = ls.train_ytime

test_Xtree = ls.test_Xtree
test_ytree = ls.test_ytree
test_Xtime = ls.test_Xtime
test_ytime = ls.test_ytime

treenames = ls.featureTreeNames
timenames = ls.featureTimeNames

meta_pl_train = ls.meta_pl_train
meta_pl_test = ls.meta_pl_test

print(np.mean(train_ytree[:, -1])) if train_ytree.any() else None
print(np.mean(train_ytime[:, -1])) if train_ytime.any() else None
print(timenames)
print(train_Xtime.shape)

1.0037484800367518
0.5140176236823112
[np.str_('FeatureLSTM_AdjClose'), np.str_('FeatureLSTM_AdjOpen'), np.str_('FeatureLSTM_AdjHigh'), np.str_('FeatureLSTM_AdjLow'), np.str_('FeatureLSTM_Volume'), np.str_('FeatureLSTM_TradedPrice')]
(74525, 60, 6)

In [53]:
meta_tr_nvda = ls.meta_pl_train.filter(pl.col("ticker") == "NVDA")
meta_tr_nvda.tail(10)

shape: (10, 56)
┌────────────┬────────┬────────┬──────────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ date       ┆ ticker ┆ Close  ┆ AdjClose ┆ … ┆ target_open ┆ target_ope ┆ target_ope ┆ target_ope │
│ ---        ┆ ---    ┆ ---    ┆ ---      ┆   ┆ _ratio_at2  ┆ n_ratio_at ┆ n_ratio_at ┆ n_ratio_at │
│ date       ┆ str    ┆ f64    ┆ f64      ┆   ┆ ---         ┆ 3          ┆ 4          ┆ 5          │
│            ┆        ┆        ┆          ┆   ┆ f64         ┆ ---        ┆ ---        ┆ ---        │
│            ┆        ┆        ┆          ┆   ┆             ┆ f64        ┆ f64        ┆ f64        │
╞════════════╪════════╪════════╪══════════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ 2025-10-24 ┆ NVDA   ┆ 186.26 ┆ 186.26   ┆ … ┆ 1.016106    ┆ 1.094689   ┆ 1.079794   ┆ 1.086636   │
│ 2025-10-27 ┆ NVDA   ┆ 191.49 ┆ 191.49   ┆ … ┆ 1.077337    ┆ 1.062678   ┆ 1.069412   ┆ 1.077855   │
│ 2025-10-28 ┆ NVDA   ┆ 201.03 ┆ 201.03   ┆ … ┆ 0.986393    ┆ 0.992644   ┆ 1.000481   ┆ 0.976055   │
│ 2025-10-29 ┆ NVDA   ┆ 207.04 ┆ 207.04   ┆ … ┆ 1.006337    ┆ 1.014282   ┆ 0.98952    ┆ 0.968901   │
│ 2025-10-30 ┆ NVDA   ┆ 202.89 ┆ 202.89   ┆ … ┆ 1.007895    ┆ 0.983289   ┆ 0.9628     ┆ 0.951417   │
│ 2025-10-31 ┆ NVDA   ┆ 202.49 ┆ 202.49   ┆ … ┆ 0.975586    ┆ 0.955258   ┆ 0.943964   ┆ 0.888601   │
│ 2025-11-03 ┆ NVDA   ┆ 206.88 ┆ 206.88   ┆ … ┆ 0.979163    ┆ 0.967586   ┆ 0.910837   ┆ 0.961133   │
│ 2025-11-04 ┆ NVDA   ┆ 198.69 ┆ 198.69   ┆ … ┆ 0.988177    ┆ 0.930221   ┆ 0.981587   ┆ 0.981813   │
│ 2025-11-05 ┆ NVDA   ┆ 195.21 ┆ 195.21   ┆ … ┆ 0.94135     ┆ 0.993331   ┆ 0.99356    ┆ 0.996436   │
│ 2025-11-06 ┆ NVDA   ┆ 188.08 ┆ 188.08   ┆ … ┆ 1.055219    ┆ 1.055462   ┆ 1.058518   ┆ 1.033261   │
└────────────┴────────┴────────┴──────────┴───┴─────────────┴────────────┴────────────┴────────────┘

In [54]:
meta_tr_nvda = ls.meta_pl_test.filter(pl.col("ticker") == "NVDA")
meta_tr_nvda.tail(10)

shape: (6, 56)
┌────────────┬────────┬────────┬──────────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ date       ┆ ticker ┆ Close  ┆ AdjClose ┆ … ┆ target_open ┆ target_ope ┆ target_ope ┆ target_ope │
│ ---        ┆ ---    ┆ ---    ┆ ---      ┆   ┆ _ratio_at2  ┆ n_ratio_at ┆ n_ratio_at ┆ n_ratio_at │
│ date       ┆ str    ┆ f64    ┆ f64      ┆   ┆ ---         ┆ 3          ┆ 4          ┆ 5          │
│            ┆        ┆        ┆          ┆   ┆ f64         ┆ ---        ┆ ---        ┆ ---        │
│            ┆        ┆        ┆          ┆   ┆             ┆ f64        ┆ f64        ┆ f64        │
╞════════════╪════════╪════════╪══════════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ 2025-11-07 ┆ NVDA   ┆ 188.15 ┆ 188.15   ┆ … ┆ 1.000231    ┆ 1.003126   ┆ 0.979191   ┆ 0.937215   │
│ 2025-11-10 ┆ NVDA   ┆ 199.05 ┆ 199.05   ┆ … ┆ 1.002895    ┆ 0.978965   ┆ 0.936999   ┆ null       │
│ 2025-11-11 ┆ NVDA   ┆ 193.16 ┆ 193.16   ┆ … ┆ 0.976139    ┆ 0.934294   ┆ null       ┆ null       │
│ 2025-11-12 ┆ NVDA   ┆ 193.8  ┆ 193.8    ┆ … ┆ 0.957132    ┆ null       ┆ null       ┆ null       │
│ 2025-11-13 ┆ NVDA   ┆ 186.86 ┆ 186.86   ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ 2025-11-14 ┆ NVDA   ┆ 190.17 ┆ 190.17   ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
└────────────┴────────┴────────┴──────────┴───┴─────────────┴────────────┴────────────┴────────────┘

In [55]:
split_Date = datetime.date(year=2025, month=10, day=1)
ls.split_dataset(
    start_date=start_train_date,
    last_train_date=split_Date,
    last_test_date=eval_date
)
lstree.split_dataset(
    start_date=start_train_date,
    last_train_date=split_Date,
    last_test_date=eval_date
)
lstime.split_dataset(
    start_date=start_train_date,
    last_train_date=split_Date,
    last_test_date=eval_date
)

In [56]:
ls.meta_pl_train.filter(pl.col("ticker") == "NVDA").head(10)

shape: (10, 56)
┌────────────┬────────┬───────┬──────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ date       ┆ ticker ┆ Close ┆ AdjClose ┆ … ┆ target_open ┆ target_open ┆ target_ope ┆ target_ope │
│ ---        ┆ ---    ┆ ---   ┆ ---      ┆   ┆ _ratio_at2  ┆ _ratio_at3  ┆ n_ratio_at ┆ n_ratio_at │
│ date       ┆ str    ┆ f64   ┆ f64      ┆   ┆ ---         ┆ ---         ┆ 4          ┆ 5          │
│            ┆        ┆       ┆          ┆   ┆ f64         ┆ f64         ┆ ---        ┆ ---        │
│            ┆        ┆       ┆          ┆   ┆             ┆             ┆ f64        ┆ f64        │
╞════════════╪════════╪═══════╪══════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ 2014-01-02 ┆ NVDA   ┆ 15.86 ┆ 0.373945 ┆ … ┆ 0.996224    ┆ 1.00944     ┆ 1.019509   ┆ 1.013845   │
│ 2014-01-03 ┆ NVDA   ┆ 15.67 ┆ 0.369465 ┆ … ┆ 1.013266    ┆ 1.023373    ┆ 1.017688   ┆ 0.998105   │
│ 2014-01-06 ┆ NVDA   ┆ 15.88 ┆ 0.374417 ┆ … ┆ 1.009975    ┆ 1.004364    ┆ 0.985037   ┆ 0.980673   │
│ 2014-01-07 ┆ NVDA   ┆ 16.14 ┆ 0.380547 ┆ … ┆ 0.994444    ┆ 0.975309    ┆ 0.970988   ┆ 0.953086   │
│ 2014-01-08 ┆ NVDA   ┆ 16.36 ┆ 0.385734 ┆ … ┆ 0.980757    ┆ 0.976412    ┆ 0.958411   ┆ 0.987585   │
│ 2014-01-09 ┆ NVDA   ┆ 15.75 ┆ 0.371352 ┆ … ┆ 0.99557     ┆ 0.977215    ┆ 1.006962   ┆ 1.013291   │
│ 2014-01-10 ┆ NVDA   ┆ 15.73 ┆ 0.37088  ┆ … ┆ 0.981564    ┆ 1.011443    ┆ 1.0178     ┆ 1.020979   │
│ 2014-01-13 ┆ NVDA   ┆ 15.36 ┆ 0.362156 ┆ … ┆ 1.03044     ┆ 1.036917    ┆ 1.040155   ┆ 1.036917   │
│ 2014-01-14 ┆ NVDA   ┆ 15.84 ┆ 0.373474 ┆ … ┆ 1.006285    ┆ 1.009428    ┆ 1.006285   ┆ 1.010685   │
│ 2014-01-15 ┆ NVDA   ┆ 16.01 ┆ 0.377482 ┆ … ┆ 1.003123    ┆ 1.0         ┆ 1.004372   ┆ 0.998126   │
└────────────┴────────┴───────┴──────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [57]:
ls.meta_pl_test.filter(pl.col("ticker") == "NVDA").tail(10)

shape: (10, 56)
┌────────────┬────────┬────────┬──────────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ date       ┆ ticker ┆ Close  ┆ AdjClose ┆ … ┆ target_open ┆ target_ope ┆ target_ope ┆ target_ope │
│ ---        ┆ ---    ┆ ---    ┆ ---      ┆   ┆ _ratio_at2  ┆ n_ratio_at ┆ n_ratio_at ┆ n_ratio_at │
│ date       ┆ str    ┆ f64    ┆ f64      ┆   ┆ ---         ┆ 3          ┆ 4          ┆ 5          │
│            ┆        ┆        ┆          ┆   ┆ f64         ┆ ---        ┆ ---        ┆ ---        │
│            ┆        ┆        ┆          ┆   ┆             ┆ f64        ┆ f64        ┆ f64        │
╞════════════╪════════╪════════╪══════════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ 2025-11-03 ┆ NVDA   ┆ 206.88 ┆ 206.88   ┆ … ┆ 0.979163    ┆ 0.967586   ┆ 0.910837   ┆ 0.961133   │
│ 2025-11-04 ┆ NVDA   ┆ 198.69 ┆ 198.69   ┆ … ┆ 0.988177    ┆ 0.930221   ┆ 0.981587   ┆ 0.981813   │
│ 2025-11-05 ┆ NVDA   ┆ 195.21 ┆ 195.21   ┆ … ┆ 0.94135     ┆ 0.993331   ┆ 0.99356    ┆ 0.996436   │
│ 2025-11-06 ┆ NVDA   ┆ 188.08 ┆ 188.08   ┆ … ┆ 1.055219    ┆ 1.055462   ┆ 1.058518   ┆ 1.033261   │
│ 2025-11-07 ┆ NVDA   ┆ 188.15 ┆ 188.15   ┆ … ┆ 1.000231    ┆ 1.003126   ┆ 0.979191   ┆ 0.937215   │
│ 2025-11-10 ┆ NVDA   ┆ 199.05 ┆ 199.05   ┆ … ┆ 1.002895    ┆ 0.978965   ┆ 0.936999   ┆ null       │
│ 2025-11-11 ┆ NVDA   ┆ 193.16 ┆ 193.16   ┆ … ┆ 0.976139    ┆ 0.934294   ┆ null       ┆ null       │
│ 2025-11-12 ┆ NVDA   ┆ 193.8  ┆ 193.8    ┆ … ┆ 0.957132    ┆ null       ┆ null       ┆ null       │
│ 2025-11-13 ┆ NVDA   ┆ 186.86 ┆ 186.86   ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ 2025-11-14 ┆ NVDA   ┆ 190.17 ┆ 190.17   ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
└────────────┴────────┴────────┴──────────┴───┴─────────────┴────────────┴────────────┴────────────┘

In [58]:
mask_train = np.ones((ls.train_Xtree.shape[0],), dtype=bool)
mask_test = np.ones((ls.test_Xtree.shape[0],), dtype=bool)
rat = 0.1
mask_train = mask_train & (np.random.rand(ls.train_Xtree.shape[0]) <= rat)
mask_test  = mask_test  & (np.random.rand(ls.test_Xtree.shape[0]) <= rat)

ls.apply_masks(mask_train, mask_test)
assert ls.train_Xtree.shape[0] == np.sum(mask_train)
assert ls.test_Xtree.shape[0] == np.sum(mask_test)